GRANT USAGE ON SCHEMA workers to app_user;
GRANT SELECT, INSERT, UPDATE, DELETE
    ON ALL TABLES IN SCHEMA workers
    TO app_user;
GRANT ALL ON ALL SEQUENCES IN SCHEMA workers TO app_user;

GRANT USAGE ON SCHEMA app to app_user;
GRANT USAGE ON SCHEMA auth to app_user;
GRANT SELECT, INSERT, UPDATE, DELETE
    ON ALL TABLES IN SCHEMA app
    TO app_user;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA app to app_user;